### ISSUE TITLE
Add menu for saved beacons

### ISSUE THREAD

**Issue by turbulator** [turbo-lab/android-beacon-mqtt#15]
- Edit
- Delete

**Comment by turbo-lab** [comment]
https://ru.stackoverflow.com/questions/450806/%D0%BA%D0%BE%D0%BD%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%BD%D0%BE%D0%B5-%D0%BC%D0%B5%D0%BD%D1%8E-%D0%B2-listview

**Comment by turbulator** [comment]
Added in 78abe7bed909c210c0d5e732e001996cad6c5dc5
