### ISSUE TITLE
Mqtt connection closed toast

### ISSUE THREAD

**Issue by rdehuyss** [turbo-lab/android-beacon-mqtt#21]
I regularly get an Android toast message saying that my mqtt connection is closed/disconnected. 

I'm using mosquito with defaults in a docker container.

I'll try to add a screenshot. 

Any idea why this is?

**Comment by turbulator** [comment]
Are you using 3G channel?

I also have such troubles when I am in 3G network. In home I use wifi connection and never got such toasts.

**Comment by rdehuyss** [comment]
Also at home when using WiFi...

**Comment by kutd** [comment]
me too

**Comment by turbulator** [comment]
#MeToo what? :)))

It looks like this toast gets too intrusive. So, I going to cut off this functionality.

**Comment by turbulator** [comment]
Done in 388ed3010654c50dc4cbea7152592a2657f303f2
