### ISSUE TITLE
%beacon% not working in topic

### ISSUE THREAD

**Issue by philsson** [turbo-lab/android-beacon-mqtt#25]
Using a topic as "presence/ble/user1/%beacon%" the topic published does not contain the name of the beacon but the string "%beacon%"

**Comment by turbulator** [comment]
You are right. I'll fix it tomorrow.

**Comment by turbulator** [comment]
Fixed in 63f9a6b19ca2d4586fa20cd89f9edfb3136b47cc

**Comment by turbulator** [comment]
Pushed to Google Play
