### ISSUE TITLE
Track params of beacon (signal strength, distance, etc)

### ISSUE THREAD

**Issue by philsson** [turbo-lab/android-beacon-mqtt#26]
It would be really helpful to get some extra data to distinguish which beacon is closest. E.g in my home I'm normally connected to at least two beacons at the same time. This makes it difficult to determine which room I am in. With signal strength this could be resolved serverside.

**Comment by turbulator** [comment]
Hello Philip!
I thought about your requirements. So, I have some ideas. After beacon was discovered we can start send "track" messages periodically with specific payload (RSSI, distance and other with user-defined format). We stop publishing when we  lost our beacon . Track interval will be the part of configuration. 

Example of timeline:
10:00 - Enter 
10:01 - Track
10:02 - Track
10:03 - Track
...
10:15 - Exit

What do you think about it?

**Comment by philsson** [comment]
I think this is good, with a JSON formatted payload we could easily add more needed information besides rssi in the future.

**Comment by ghost** [comment]
That indeed would be great!

**Comment by turbulator** [comment]
Done in dfad3551bf81d29fc7f79ae66c38240984c9b6a1
