### ISSUE TITLE
Beacons are lost if phone is restarted

### ISSUE THREAD

**Issue by dermotduffy** [turbo-lab/android-beacon-mqtt#28]
Version: 0.3

Beacons added are lost upon phone restart (don't show up in main view, nothing is reported over mqtt and need to be re-added). Repeatable.

**Comment by turbulator** [comment]
Hello! Thanks for you feedback!
I have to ask something.

Are you a new user (or reinstall app) or just updated from 0.2?

**Comment by dermotduffy** [comment]
Hmm. I had it installed/uninstalled a few times, so difficult to answer for sure. I _think_ I had it uninstalled for a few days (the old version), then reinstalled (and was surprised that it looked new and shiny -- nice work on the UI!).

**Comment by turbulator** [comment]
Done in e6ce9e0f1d7834a6725f0146219d74421090e95e
